name: Pull-request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: groups-dependency-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            groups-dependency-cache-

      - name: Build and Run test cases
        run: mvn clean install


      - name: Save the build artifact
        run: cd service && mvn play2:dist

      - name: Save Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: groups-dependency-cache-${{ hashFiles('**/pom.xml') }}

      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: group-service
          path: service/target/group-service-1.0.0-dist.zip

  sonar-analysis:
    runs-on: ubuntu-latest
    needs: run-test-cases
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: groups-dependency-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            groups-dependency-cache-

      - name: xml report
        run: |
          ls reports/target/jacoco/

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=GayathriSrividya_groups_service \
            -Dsonar.organization=gayathrisrividya \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.exclusions=**/cassandra-utils/**,**/platform-cache/**,**/sb-actor/**,**/sb-telemetry-utils/**,**/sb-utils/**,**/models/**,**/bean/*,**/sb-common/** \
            -Dsonar.coverage.jacoco.xmlReportPaths=/home/runner/work/groups-service/groups-service/reports/target/jacoco/jacoco.xml 
             
      - name: list files
        run: |
          ls -R reports/target/jacoco && \
          cat reports/target/jacoco/jacoco.xml
          

